// Generated by the WOLips Templateengine Plug-in at 05.11.2006 12:11:41

import com.webobjects.appserver.WOApplication;
import com.webobjects.foundation.NSLog;

public class Application extends WOApplication {
    
    public static void main(String argv[]) {
        WOApplication.main(argv, Application.class);
    }

    public Application() {
        super();
        NSLog.out.appendln("Welcome to " + this.name() + " !");
        /* ** put your initialization code in here ** */
    }
}