// Generated by the WOLips Templateengine Plug-in at 05.11.2006 13:26:40

import com.webobjects.appserver.*;

public class ExampleFrontendComponent extends WOComponent {

    public ExampleFrontendComponent(WOContext context) {
        super(context);
    }

}