// Generated by the WOLips Templateengine Plug-in at 05.11.2006 13:27:22

import com.webobjects.appserver.*;

public class ExampleAdminComponent extends WOComponent {

    public ExampleAdminComponent(WOContext context) {
        super(context);
    }

}