// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $basePackage;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
