// Generated by the Maven Archetype Plug-in
package ${package}.app;

import com.webobjects.foundation.NSLog;

#if($WonderSupport == "no")
import com.webobjects.appserver.WOApplication;
#set( $applicationClass = "WOApplication" )
#else
import er.extensions.ERXApplication;
#set( $applicationClass = "ERXApplication" )
#end

public class Application extends $applicationClass {
	public static void main(String[] argv) {
		${applicationClass}.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + name() + " !");
		/* ** put your initialization code in here ** */
	}
}
