/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_objectstyle_wolips_goodies_core_mac_MacRefreshMonitor */

#ifndef _Included_org_objectstyle_wolips_goodies_core_mac_MacRefreshMonitor
#define _Included_org_objectstyle_wolips_goodies_core_mac_MacRefreshMonitor
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_org_objectstyle_wolips_goodies_core_mac_MacRefreshMonitor_unmonitor
  (JNIEnv *, jobject, jint, jstring, jobject);

JNIEXPORT jint JNICALL Java_org_objectstyle_wolips_goodies_core_mac_MacRefreshMonitor_monitor
  (JNIEnv *, jobject, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
