// Generated by the WebObjects Wizard Tue Mar 05 11:51:43 Europe/Paris 2002

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class Main extends WOComponent {


    public Main(WOContext context) {
        super(context);
    }

    public String HelloString() {
        String hello= "Hello World!";
        return hello;
    }

}
