// Generated by the WOLips Templateengine Plug-in at 05.11.2006 12:12:01

import com.webobjects.appserver.*;

import example.ExampleLogic;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context);
    }
    
    public int logicResult() {
        ExampleLogic exampleLogic = new ExampleLogic();
        int result = exampleLogic.plus(1, 2);
        return result;
    }


}