// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $basePackage;

import er.extensions.ERXSession;

public class Session extends ERXSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
