// Generated by the ${WOLipsContext.getPluginName()} at ${Date}
package $componentsPackage;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
}
