// Generated by the Maven Archetype Plug-in
package ${package}.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
		super();
	}
}
