// Generated by the Maven Archetype Plug-in
package ${package}.app;

import ${package}.components.Main;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;
#if($WonderSupport == "no")
import com.webobjects.appserver.WODirectAction;
#set( $directActionClass = "WODirectAction" )
#else
import er.extensions.appserver.ERXDirectAction;
#set( $directActionClass = "ERXDirectAction" )
#end

public class DirectAction extends $directActionClass {
	public DirectAction( WORequest request ) {
		super( request );
	}

	public WOActionResults defaultAction() {
		return pageWithName( Main.class.getName() );
	}
}
